# Generated by Django 6.0.4 on 2026-05-04 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('grasas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('grasas', models.IntegerField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.plannutricional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
