# Generated by Django 6.0.4 on 2026-05-04 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('xp_requerida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('xp_min', models.IntegerField()),
                ('xp_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_total', models.IntegerField()),
                ('racha_actual', models.IntegerField()),
                ('mejor_racha', models.IntegerField()),
                ('calorias_totales', models.IntegerField()),
                ('entrenamientos', models.IntegerField()),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('rango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.rango')),
            ],
        ),
    ]
