# Generated by Django 6.0.4 on 2026-05-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_avatar_imagen_url_avatar_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
